version:'3.8'
services:
  web:
    image: payslip:$BUILD_ID
    container_name: payslip
    ports:
      - 8080:8080
    restart_always: yes
    networks:
       - front_end
    volumes:
      - /opt/cont_vol/: /var/lib/tomcat/webapps/ 
volumes:
  /opt/cont_vol/:
    driver: local
networks:
   front_end: 
     driver: bridge
